# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        pwd
        ls
    
    - name: LaTeX Render Action for Github
      uses: AffineParameter/latex-action@a0.2.1
      with:
        # The root LaTeX file to be compiled
        root_file: latex-starter/report/main.tex
        # The working directory for the LaTeX engine
        working_directory: # optional
        # The LaTeX engine to be invoked
        compiler: latexmk # optional, default is latexmk
        # Extra arguments to be passed to the LaTeX engine
        args: -pdf -file-line-error -interaction=nonstopmode # optional, default is -pdf -file-line-error -interaction=nonstopmode
        # Install extra packages by apk
        extra_system_packages: # optional
        # Utilize extra local packages given a local directory
        extra_local_packages: # optional
